services:
  web:
    build: .
    ports:
      - "5020:5020"
    depends_on:
      - redis
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_LIBRARY_SECTION_ID=${PLEX_LIBRARY_SECTION_ID}
      - client_id=${client_id}
      - client_secret=${client_secret}
      - playlist_ids=${playlist_ids}
    command: flask run --host=0.0.0.0
    network_mode: host

  celery:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER=${CELERY_BROKER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_LIBRARY_SECTION_ID=${PLEX_LIBRARY_SECTION_ID}
      - client_id=${client_id}
      - client_secret=${client_secret}
      - playlist_ids=${playlist_ids}
    command: celery -A app.celery worker --loglevel=info
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    network_mode: host